technology_colors = {
    "": "rgba(255,255,255,0)",
    # Electricity
    "Non-RES": "#B5C6CF",
    "Fossil fuels": "#B5C6CF",
    "Coal and other non-RES": "#B5C6CF",
    "Coal": "#B5C6CF",
    "Hard coal": "#B5C6CF",
    "Hard coal SC": "#B5C6CF",
    "Hard coal CHP": "#B5C6CF",
    "Lignite": "#72A0B7",
    "Lignite SC": "#72A0B7",
    "Lignite CHP": "#72A0B7",
    "Natural gas": "#4B7689",
    "Natural gas CCGT": "#4B7689",
    "Natural gas CCGT CHP": "#4B7689",
    "Natural gas OCGT": "#263b46",
    "Coke-oven gas": "#263b46",
    "Oil": "#263B46",
    "Nuclear": "#d6c0bd",
    "Nuclear large": "#f4a6a5",
    "Nuclear small": "#e3201f",
    "Other RES": "#816d66",
    "Biomass/biogas": "#263b46",
    "Biomass and biogas": "#816d66",
    "Biomass and biogas CHP": "#816d66",
    "Biomass wood chips": "#d6c0bd",
    "Biomass wood chips CHP": "#d6c0bd",
    "Biomass straw": "#ab9d99",
    "Biomass straw CHP": "#ab9d99",
    "Biogas": "#816d66",
    "Biogas CHP": "#816d66",
    "Biogas engine": "#816d66",
    "Biogas engine CHP": "#816d66",
    "Biogas plant": "#816d66",
    "Biogas storage": "#816d66",
    "Hydro ROR": "#573c33",
    "Wind": "#69F0AE",
    "Wind onshore": "#B9F6CA",
    "Wind offshore": "#01E677",
    "PV": "#EC8CFD",
    "Solar": "#EC8CFD",
    "PV roof": "#F3B3FD",
    "PV ground": "#E040FB",
    "Storage loss": "#767778",
    "Hydro PSH/Battery": "#458aff",
    "Hydro PSH": "#82b1ff",
    "Hydro PSH dispatch": "#82b1ff",
    "Hydro PSH store": "#82b1ff",
    "Battery": "#458aff",
    "Battery dispatch": "#458aff",
    "Battery store": "#458aff",
    "Battery large": "#458aff",
    "Battery large dispatch": "#458aff",
    "Battery large store": "#458aff",
    "Battery small": "#2979ff",
    "Battery small dispatch": "#2979ff",
    "Battery small store": "#2979ff",
    "BEV V2G": "#153d80",
    "BEV charger": "#153d80",
    "BEV charger - recovered": "#153d80",
    "Hydrogen": "#2ad4ff",
    "Hydrogen CCGT": "#2ad4ff",
    "Hydrogen CCGT CHP": "#2ad4ff",
    "Hydrogen OCGT": "#2ad4ff",
    "Interconnector": "#767778",
    "Import/export": "#767778",
    "Import or export": "#767778",
    "Net import or export": "#767778",
    "Net import": "#767778",
    "Net export": "#767778",
    "Import": "#767778",
    "Export": "#767778",
    "DSR": "#49494b",
    # Light vehicles
    "BEV charger - net": "#2979ff",
    "ICE vehicle": "#767778",
    "BEV": "#2979ff",
    # Hydrogen
    "Natural gas reforming": "#4B7689",
    "Electrolyser": "#80e5ff",
    "Hydrogen storage": "#00aad4",
    "Hydrogen storage dispatch": "#00aad4",
    "Hydrogen storage store": "#00aad4",
    # Heat
    "CHP": "#767778",
    "Hard coal CHP": "#B5C6CF",
    "Lignite CHP": "#72A0B7",
    "Natural gas CHP": "#4B7689",
    "Other CHP": "#131e23",
    "Conventional heating plant": "#263b46",
    "Heat-only boiler": "#263b46",
    "Biomass wood chips CHP": "#d6c0bd",
    "Biomass straw CHP": "#ab9d99",
    "Biogas CHP": "#816d66",
    "Power-to-heat centralised": "#e94d4c",
    "Heat pump large": "#f4a6a5",
    "Resistive heater large": "#e94d4c",
    "Conventional boiler": "#767778",
    "Hard coal boiler": "#B5C6CF",
    "Natural gas boiler": "#4B7689",
    "Oil boiler": "#263B46",
    "Biomass boiler": "#816d66",
    "Power-to-heat": "#f4a6a5",
    "Power-to-heat decentralised": "#f4a6a5",
    "Heat pump small": "#f4a6a5",
    "Resistive heater small": "#e94d4c",
    "Heat storage store": "#aa1817",
    "Heat storage dispatch": "#aa1817",
    "Heat storage large": "#aa1817",
    "Heat storage large dispatch": "#aa1817",
    "Heat storage large store": "#aa1817",
    "Heat storage small": "#aa1817",
    "Heat storage small dispatch": "#aa1817",
    "Heat storage small store": "#aa1817",
    "District heating loss": "#49494b",
    "District heating distribution": "#49494b",
    # Final use
    "Electricity final use": "#b6b6b7",
    "Heat final use": "#b6b6b7",
    "Hydrogen final use": "#b6b6b7",
    "Light vehicles final use": "#b6b6b7",
    # All
    "Virtual DSR": "#1b1c1e",
    "Total": "#C1843D",
}


technology_names_pl = {
    "": "",
    # Electricity
    "Non-RES": "Nie-OZE",
    "Fossil fuels": "Paliwa kopalne",
    "Coal and other non-RES": "Węgiel i inne nie-OZE",
    "Coal": "Węgiel",
    "Hard coal": "Węgiel kamienny",
    "Hard coal SC": "Węgiel kamienny - nadkrytyczne",
    "Hard coal CHP": "Węgiel kamienny - kogeneracja",
    "Lignite": "Węgiel brunatny",
    "Lignite SC": "Węgiel brunatny - nadkrytyczne",
    "Lignite CHP": "Węgiel brunatny - kogeneracja",
    "Natural gas": "Gaz ziemny",
    "Natural gas CCGT": "Gaz ziemny CCGT",
    "Natural gas CCGT CHP": "Gaz ziemny CCGT - kogeneracja",
    "Natural gas OCGT": "Gaz ziemny OCGT",
    "Coke-oven gas": "Gaz koksowniczy",
    "Oil": "Olej opałowy",
    "Nuclear": "Energia jądrowa",
    "Nuclear large": "Energia jądrowa - duża",
    "Nuclear small": "Energia jądrowa - mała",
    "Other RES": "Inne OZE",
    "Biomass/biogas": "Biomasa/biogaz",
    "Biomass and biogas": "Biomasa i biogaz",
    "Biomass and biogas CHP": "Biomasa i biogaz - kogeneracja",
    "Biomass wood chips": "Biomasa drzewna",
    "Biomass wood chips CHP": "Biomasa drzewna - kogeneracja",
    "Biomass straw": "Biomasa agro",
    "Biomass straw CHP": "Biomasa agro - kogeneracja",
    "Biogas": "Biogaz",
    "Biogas CHP": "Biogaz - kogeneracja",
    "Biogas engine": "Silnik na biogaz",
    "Biogas engine CHP": "Silnik na biogaz - kogeneracja",
    "Biogas plant": "Biogazownia",
    "Biogas storage": "Magazyn biogazu",
    "Hydro ROR": "Woda - przepływowe",
    "Wind": "Wiatr",
    "Wind onshore": "Wiatr - ląd",
    "Wind offshore": "Wiatr - morze",
    "PV": "PV",
    "Solar": "Słońce",
    "PV roof": "PV - dach",
    "PV ground": "PV - gruntowe",
    "Storage loss": "Straty magazynów",
    "Hydro PSH/Battery": "ESP/Baterie",
    "Hydro PSH": "Woda - szczytowo-pompowe",
    "Hydro PSH dispatch": "ESP - generacja",
    "Hydro PSH store": "ESP - pompowanie",
    "Battery": "Baterie",
    "Battery dispatch": "Baterie - rozładowanie",
    "Battery store": "Baterie - ładowanie",
    "Battery large": "Baterie duże",
    "Battery large dispatch": "Baterie duże - rozładowanie",
    "Battery large store": "Baterie duże - ładowanie",
    "Battery small": "Baterie małe",
    "Battery small dispatch": "Baterie małe - rozładowanie",
    "Battery small store": "Baterie małe - ładowanie",
    "BEV V2G": "BEV V2G",
    "BEV charger": "BEV - ładowanie",
    "BEV charger - recovered": "BEV - energia odzyskana",
    "Hydrogen": "Wodór",
    "Hydrogen CCGT": "Wodór CCGT",
    "Hydrogen CCGT CHP": "Wodór CCGT - kogeneracja",
    "Hydrogen OCGT": "Wodór OCGT",
    "Interconnector": "Interkonektor",
    "Import/export": "Import/eksport",
    "Import or export": "Import lub eksport",
    "Net import or export": "Import/eksport netto",
    "Net import": "Import netto",
    "Net export": "Eksport netto",
    "Import": "Import",
    "Export": "Eksport",
    "DSR": "DSR",
    # Hydrogen
    "Natural gas reforming": "Reforming gazu ziemnego",
    "Electrolyser": "Elektroliza",
    "Hydrogen storage": "Magazyn wodoru",
    "Hydrogen storage dispatch": "Magazyn wodoru - rozładowanie",
    "Hydrogen storage store": "Magazyn wodoru - ładowanie",
    # Light vehicles
    "BEV charger - net": "BEV - netto",
    "ICE vehicle": "Silnik spalinowy",
    "BEV": "BEV",
    # Heat
    "CHP": "Kogeneracja",
    "Hard coal CHP": "Węgiel kamienny - kogeneracja",
    "Lignite CHP": "Węgiel brunatny - kogeneracja",
    "Natural gas CHP": "Gaz ziemny - kogeneracja",
    "Conventional heating plant": "Ciepłownia konwencjonalna",
    "Heat-only plant": "Kocioł szczytowy",
    "Heat-only boiler": "Kocioł szczytowy",
    "Biomass wood chips CHP": "Biomasa drzewna - kogeneracja",
    "Biomass straw CHP": "Biomasa agro - kogeneracja",
    "Biogas CHP": "Biogaz - kogeneracja",
    "Other CHP": "Inne nie-OZE - kogeneracja",
    "Power-to-heat centralised": "Power-to-heat - systemowe",
    "Heat pump large": "Pompa ciepła duża",
    "Resistive heater large": "Kocioł elektrodowy duży",
    "Conventional boiler": "Kocioł konwencjonalny",
    "Hard coal boiler": "Kocioł na węgiel kamienny",
    "Natural gas boiler": "Kocioł na gaz ziemny",
    "Oil boiler": "Kocioł na olej",
    "Biomass boiler": "Kocioł na biomasę",
    "Power-to-heat": "Power-to-heat",
    "Power-to-heat decentralised": "Power-to-heat - indywidualne",
    "Heat pump small": "Pompa ciepła mała",
    "Resistive heater small": "Grzałka szczytowa",
    "Heat storage dispatch": "Magazyn ciepła - rozładowanie",
    "Heat storage store": "Magazyn ciepła - ładowanie",
    "Heat storage large": "Magazyn ciepła duży",
    "Heat storage large dispatch": "Magazyn ciepła duży - rozładowanie",
    "Heat storage large store": "Magazyn ciepła duży - ładowanie",
    "Heat storage small": "Magazyn ciepła mały",
    "Heat storage small dispatch": "Magazyn ciepła mały - rozładowanie",
    "Heat storage small store": "Magazyn ciepła mały - ładowanie",
    "District heating loss": "Straty ciepła w sieci",
    "District heating distribution": "Dystrybucja ciepła sieciowego",
    # Final use
    "Electricity final use": "Elektryczność - zużycie końcowe",
    "Heat final use": "Ciepło - zużycie końcowe",
    "Hydrogen final use": "Wodór - zużycie końcowe",
    "Light vehicles final use": "Lekkie pojazdy - zużycie końcowe",
    # All
    "Virtual DSR": "DSR wirtualne",
    "Total": "Razem",
}


if __name__ == "__main__":
    import os
    from pypsa_pl.config import data_dir

    os.makedirs(data_dir("clean", "flourish"), exist_ok=True)

    with open(data_dir("clean", "flourish", "colors_en.txt"), "w") as f:
        for tech, color in technology_colors.items():
            if tech == "":
                continue
            f.write(f"{tech}: {color}\n")

    with open(data_dir("clean", "flourish", "colors_pl.txt"), "w") as f:
        for tech, color in technology_colors.items():
            if tech == "":
                continue
            tech_pl = technology_names_pl[tech]
            f.write(f"{tech_pl}: {color}\n")
